import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";

import { RouterOutputs, api } from "~/utils/api";

const CreatePostWizard = () => {

  const { user } = useUser()

  if(!user) return null

  return <div className="flex gap-3 ">
    <img src = {user.profileImageUrl} alt = 'profile image' className="w-14 h-14 rounded-full"/>
    <input placeholder='type some emojis' className ='bg-transparent grow outline-none' />
  </div>
}

type PostWithUser = RouterOutputs["post"]["getAll"][number]

const PostView = (props: PostWithUser) => {
  const {post, author} = props
  return <div key={post.id} className="flex p-4 border-b border-slate-400 gap-3">
    <img src={author.profileImageUrl} className="w-14 h-14 rounded-full"/>
    <div className = "flex flex-col">
      <div className ='flex text-slate-300 font-bold gap-1'><span>{`@${author.username}`}</span> <span className='font-thin'>{` · 1 hour ago`}</span></div>
    <span>{post.content}</span></div></div>
}

export default function Home() {

  const user = useUser() 

  const {data} = api.post.getAll.useQuery()

  console.log(user)
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
      <div className="w-full  md:max-w-2xl border-x border-slate-400">
      <div className="border-b border-slate-400 p-4">
      {user.isSignedIn ? <div ><CreatePostWizard/></div> : <div><SignInButton></SignInButton></div>}
      </div>
      <div className="flex flex-col">
        {data?.map ((fullPost) => (<PostView {...fullPost} key = {fullPost.post.id}/>))}
      </div>
      </div>
      </main>
    </>
  );
}
